name: chexnet-with-localization
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - cudatoolkit=10.0.130
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.1.1q
  - pip=22.1.2
  - pycparser=2.21
  - python=3.7.13
  - pytorch=1.0.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - vc=14.2
  - vs2015_runtime
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - aiofiles==0.8.0
    - anyio==3.6.1
    - click==8.1.3
    - colorama==0.4.5
    - cycler==0.11.0
    - dicom2jpg==0.1.9
    - fastapi==0.79.0
    - fonttools==4.34.4
    - h11==0.13.0
    - highdicom==0.18.2
    - httptools==0.4.0
    - idna==3.3
    - imageio==2.20.0
    - importlib-metadata==4.12.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - networkx==2.6.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pillow==8.4.0
    - pillow-jpls==1.1.0
    - pydantic==1.9.1
    - pydicom==2.3.0
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.1
    - pylibjpeg-openjpeg==1.2.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-multipart==0.0.5
    - pywavelets==1.3.0
    - pyyaml==6.0
    - scikit-image==0.17.2
    - scipy==1.2.1
    - sniffio==1.2.0
    - starlette==0.19.1
    - tifffile==2021.11.2
    - torchvision==0.2.2
    - tqdm==4.19.9
    - typing-extensions==4.3.0
    - uvicorn==0.18.2
    - watchfiles==0.16.1
    - websockets==10.3
    - zipp==3.8.1
