name: chexnet-with-localization
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - cudatoolkit=10.0.130
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - pip=22.1.2
  - pycparser=2.21
  - python=3.7.13
  - pytorch=1.0.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - wheel=0.37.1
  - pip:
    - cycler==0.11.0
    - dicom2jpg==0.1.9
    - fonttools==4.34.4
    - highdicom==0.18.4
    - imageio==2.20.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - networkx==2.6.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pillow==8.4.0
    - pillow-jpls==1.1.0
    - pydicom==2.3.0
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.1
    - pylibjpeg-openjpeg==1.2.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.3.0
    - scikit-image==0.17.2
    - scipy==1.2.1
    - tifffile==2021.11.2
    - torchvision==0.2.2
    - tqdm==4.19.9
    - typing-extensions==4.3.0
    - opencv-python==4.6.0.66
